Models/CustomError.cs
namespace BlogProject.Models
{
    public class CustomError
    {
        public int  code { get; set;}
        public string message { get; set;}
    }
}

Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogProject.Data;
using BlogProject.Models;
using BlogProject.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace BlogProject.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly UserManager<BlogUser> _userManager;
        public BlogsController(ApplicationDbContext context, IImageService imageService, UserManager<BlogUser> dataService)
        {
            _context = context;
            _imageService = imageService;
            _userManager = dataService;
        }

        // GET: Blogs

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Blogs.Include(b => b.BlogUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Blogs/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.BlogUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Image")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                blog.Created = DateTime.Now;
                blog.BlogUserId = _userManager.GetUserId(User);
                blog.ImageData = await _imageService.EncodeImageAsync(blog.Image);
                blog.ContentType = _imageService.ContentType(blog.Image);
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id", blog.BlogUserId);
            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Blog blog, IFormFile newImage)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var newBlog = await _context.Blogs.FindAsync(blog.Id);

                    newBlog.Updated = DateTime.Now;

                    if (newBlog.Name != blog.Name)
                    {
                        newBlog.Name = blog.Name;
                    }

                    if (newBlog.Description != blog.Description)
                    {
                        newBlog.Description = blog.Description;
                    }

                    if (newImage is not null)
                    {
                        newBlog.ImageData = await _imageService.EncodeImageAsync(newImage);
                    }
                    

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id", blog.BlogUserId);
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.BlogUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogProject.Data;
using BlogProject.Models;
using BlogProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using BlogProject.Enums;
using BlogProject.ViewModels;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BlogProject.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ISlugService _slugService;
        private readonly IImageService _imageService;
        private readonly UserManager<BlogUser> _userManager;
        private readonly BlogSearchService _blogSearchService;


        public PostsController(ApplicationDbContext context, ISlugService slugService, IImageService imageService, UserManager<BlogUser> userManager, BlogSearchService blogSearchService)
        {
            _context = context;
            _slugService = slugService;
            _imageService = imageService;
            _userManager = userManager;
            _blogSearchService = blogSearchService;
        }



        public async Task<IActionResult> SearchIndex(int? page, string searchTerm)
        {
            ViewData["SearchTerm"] = searchTerm;
            var pageNubmer = page ?? 1;
            var pageSize = 5;

            var posts = _blogSearchService.Search(searchTerm);

            return View(await posts.ToPagedListAsync(pageNubmer, pageSize));
        }


        // GET: Posts
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts.Include(p => p.Blog).Include(p => p.BlogUser);
            return View(await applicationDbContext.ToListAsync());
        }

        //BlogPostIndex
        public async Task<IActionResult> BlogPostIndex(int? id, int? page)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pageNumber = page ?? 1;

            var pageSize = 4;

            //var posts = _context.Posts.Where(p => p.BlogId == id).ToList();

            var posts = await _context.Posts
                .Where(p => p.BlogId == id && p.ReadyStatus == ReadyStatus.ProductionReady)
                .OrderByDescending(p => p.Created)
                .ToPagedListAsync(pageNumber, pageSize);

            return View(posts);
        }




        public async Task<IActionResult> Details(string slug)
        {
            ViewData["Title"] = "Post Deatils Page";
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Blog)
                .Include(p => p.BlogUser)
                .Include(p => p.Tags)
                .Include(p => p.Comments)
                .ThenInclude(c => c.BlogUser)
                .FirstOrDefaultAsync(m => m.Slug == slug);

            if (post == null) 
            {
                return NotFound();
            }

     
            var dataVm = new PostDetailViewModel()
            {
                Post = post,
                Tags = _context.Tags
                       .Select(t => t.Text.ToLower())
                       .Distinct().ToList()
            };
         

            ViewData["HeaderImage"] = _imageService.DecodeImage(post.ImageData, post.ContentType);
            ViewData["MainText"] = post.Title;
            ViewData["SubText"] = post.Abstract;
            return View(dataVm);
        }




        // GET: Posts/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name");
            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("BlogId,Title,Abstract,Content,ReadyStatus,Image")] Post post, List<string> tagValues)
        {
            if (ModelState.IsValid)
            {
                post.Created = DateTime.Now;

                var authorId = _userManager.GetUserId(User);
                post.BlogUserId = authorId;

                // Use The _imageService To Store The Incoming User Specified Image 
                post.ImageData = await _imageService.EncodeImageAsync(post.Image);
                post.ContentType = _imageService.ContentType(post.Image);

                var slug = _slugService.UrlFriendly(post.Title);

                //Create A Variable To Store Weather An Error Occoured
                var validationError = false;


                //Dectect Incoming Duplicate Slugs
                if (string.IsNullOrEmpty(slug))
                {
                    validationError = true;
                    ModelState.AddModelError("", "The Title You Provided Cannot Be Used As It Results In A Empty Slug");
                }

                //Dectect Incoming Duplicate Slugs
                else if (!_slugService.IsUnique(slug))
                {
                    validationError = true;
                    ModelState.AddModelError("Title", "The Title You Provided Cannot Be Used As Is Results In A Duplicate Slug");
                }


                //else if (slug.Contains("test"))
                //{
                //    validationError = true;
                //    ModelState.AddModelError("", "Are You Testing Again?");
                //    ModelState.AddModelError("Title", "The Title Cannot Contain The Word Test");
                //}


                if (validationError)
                {
                    ViewData["TagValues"] = string.Join(",", tagValues);
                    return View(post);
                }

                post.Slug = slug;



                _context.Add(post);
                await _context.SaveChangesAsync();

                // Loop Over The Incoming List Of String
                foreach (var tagText in tagValues)
                {
                    _context.Add(new Tag()
                    {
                        PostId = post.Id,
                        BlogUserId = authorId,
                        Text = tagText
                    });
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Description", post.BlogId);

            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var post = await _context.Posts.Include(p => p.Tags).FirstOrDefaultAsync(p => p.Id == id);


            if (post == null)
            {
                return NotFound();
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name", post.BlogId);
            ViewData["TagValues"] = string.Join(",", post.Tags.Select(t => t.Text));

            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogId,Title,Abstract,Content,ReadyStatus")] Post post, IFormFile newImage, List<string> tagValues)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // The Original Post
                    var originalPost = await _context.Posts.Include(p => p.Tags).FirstOrDefaultAsync(p => p.Id == post.Id);

                    originalPost.Updated = DateTime.Now;
                    originalPost.Title = post.Title;
                    originalPost.Abstract = post.Abstract;
                    originalPost.Content = post.Content;
                    originalPost.ReadyStatus = post.ReadyStatus;

                    var newSlug = _slugService.UrlFriendly(post.Title);
                    if (newSlug != originalPost.Slug)
                    {
                        if (_slugService.IsUnique(newSlug))
                        {
                            originalPost.Title = post.Title;
                            originalPost.Slug = newSlug;

                        }
                        else
                        {
                            ModelState.AddModelError("Title", "This Title Cannot Be Used As It Results In A Duplicate Slug");
                            ViewData["TagValues"] = string.Join(",", post.Tags.Select(t => t.Text));
                            return View(post);
                        }
                    }

                    if (newImage is not null)
                    {
                        originalPost.ImageData = await _imageService.EncodeImageAsync(newImage);
                        originalPost.ContentType = _imageService.ContentType(newImage);
                    }

                    // Remove All Tags Previously Associated With This Post
                    _context.Tags.RemoveRange(originalPost.Tags);

Views/Shared/CustomError.cshtml
@model BlogProject.Models.CustomError


<div class="d-flex flex-column justify-content-center">
    <div class="row row-cols-1">
        <div class="col text-center">
            <img src="/images/oops.png" alt="Page not found" class="img-fluid" height="100" />
        </div>
        <div class="col text-center display-5 my-3 fw-bold">@Model.code</div>
        <div class="col text-center h4">
            @Model.message
        </div>
        <div class="col text-center mt-3">
            <a asp-action="Index" asp-controller="Home" class="btn btn-primary btn-lg rounded-pill">
                Go To Homepage
            </a>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - Blog Project</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/images/faviconBlog.png" width="512x512" rel="icon" type="image/png">
    <link href="/images/faviconBlog.png" width="32x32" rel="icon" type="image/png">
    <link href="/images/faviconBlog.png" width="16x16" rel="icon" type="image/png">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">


    <!--Dev Icons-->
    <link href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha384-xeJqLiuOvjUBq3iGOjvSQSIlwrpqjSHXpduPd6rQpuiM3f5/ijby8pCsnbu5S81n" crossorigin="anonymous">
    <!--SummmerNote-->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

    <!--Custom CSS-->
    <link href="~/css/Custom.css" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="~/css/main.css" rel="stylesheet" />
  
</head>

<body>

    <!-- ======= Header ======= -->
@*    <section id="topbar" class="topbar d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope d-flex align-items-center">
                    <a href="mailto:contact@example.com">contact@example.com</a>
                </i>
                <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
            </div>
            <div class="social-links d-none d-md-flex align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="instagram"><i class="bi bi-linkedin"></i></a>
            </div>
        </div>
    </section>*@
    <!-- End Top Bar -->


    <header id="header" class="header d-flex align-items-center">

        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                  <img src="/images/bakerblogpencil.png"  alt="">
              @*  <h1>Baker Blog</h1>*@
            </a>
        
            <nav id="navbar" class="navbar">
               
                <ul>

                    <li> <a asp-controller="Home" asp-action="Index" class="nav-link btn btn-link ">Home</a></li>
                    <li>    <a asp-controller="Home" asp-action="Contact" class="nav-link btn btn-link ">Contact</a></li>
                    <li>    <a asp-controller="Home" asp-action="About" class="nav-link btn btn-link ">About</a></li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-controller="Blogs" asp-action="Create" class="nav-link btn btn-link ">Create Blog</a></li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-controller="Posts" asp-action="Create" class="nav-link btn btn-link ">Create Post</a></li>
                    }
                    @if (User.IsInRole("Administrator") || (User.IsInRole("Moderator")))
                    {
                        <li><a asp-controller="Comments" asp-action="Index" class="nav-link btn btn-link ">Delete Comments</a></li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-controller="Posts" asp-action="Index" class="nav-link btn btn-link ">Delete Post</a></li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-controller="Blogs" asp-action="Index" class="nav-link btn btn-link ">Delete Blog</a></li>
                    }

                    <li class="dropdown">
                        <a class="nav-link btn btn-link">
                            <span>Sign In Or Register</span> <i class="bi bi-chevron-down dropdown-indicator"></i>
                        </a>
                        <partial name="_LoginPartial" name="DisplayName" />
                    </li>



                </ul>
            </nav>
            <!-- .navbar -->
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

        </div>
    </header>
    <!-- End Header -->

    <main id="main">
   
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="row d-flex">
                <div class="container text-center py-5 ">
                    <h1 class="mb-4 text-white">Benjamin Baker's Blog</h1>  
                    <p class="text-white"> Built Using</p>
                     <div class="col-12">
                         <div class="row d-flex justify-content-center">
                            <img src="/images/csharpalt.png" class="img-fluid" style="height:90px;" />
                            <img src="/images/dotnetmvcalt.png" class="img-fluid" style="height:90px;" />
                            <img src="/images/pgadminlogo.png" class="img-fluid" style="height:90px;" />
                            <img src="/images/htmlcssjslogo.png" class="img-fluid" style="height:90px;" />
                            <img src="/images/bootstraplogo.png" class="img-fluid" style="height:90px;" />
                            
                         </div>
                     </div>
                    <div class="mx-auto mt-3" style="width: 100%; max-width: 600px;">
                        <form class="d-flex" asp-action="SearchIndex" asp-controller="Posts">
                            <input class="form-control border-light" type="search" style="padding: 30px;" placeholder="Search Blogs"
                                   aria-label="Search" name="SearchTerm">
                            <button class="btn btn-primary px-3" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>


        <!-- ======= Blog Section ======= -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">

        
                
                @RenderBody()

            </div>
        </section><!-- End Blog Section -->

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-5 col-md-12 footer-info">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <img src="/images/bakerblogpencil.png" alt="">
                    </a>
                    <p>
                        My personal blog. Feel free to look around and leave a comment if you enjoy what you see!
                    </p>
                    <div class="social-links d-flex mt-4">
                        <a href="https://github.com/Baker-Developer" target="_blank" class="github"><i class="bi bi-github"></i></a>
                        <a href="https://www.linkedin.com/in/benjamin-baker-7426a11ab/" target="_blank" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Home Page</a></li>
                        <li><a href="https://bakerportfolio.netlify.app/">My Portfolio</a></li>
                      
                    </ul>
                </div>
@*
                <div class="col-lg-2 col-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Web Development</a></li>
                        <li><a href="#">Product Management</a></li>
                        <li><a href="#">Marketing</a></li>
                        <li><a href="#">Graphic Design</a></li>
                    </ul>
                </div>*@

                <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>Contact Me</h4>
                    <p>
                         
                        Conway, AR 72034<br>
                        United States <br><br>
                        <strong>Phone:</strong> 501-339-3105<br>
                        <strong>Email:</strong> benjamin@bakermedical.net<br>
                    </p>

                </div>

            </div>
        </div>

        @*      <div class="container mt-4">
        <div class="copyright">
        &copy; Copyright <strong><span>Impact</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
        </div>
        *@
    </footer>
    <!-- End Footer -->
    @*  <a href="#" class="scroll-top d-flex align-items-center justify-content-center">
    <i class="bi bi-arrow-up-short"></i>
    </a>*@

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    @*    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>*@

    <!--Sweet Alert 2 CDN-->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/vendor/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <!--SummerNote Script-->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>


    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>